### ISSUE TITLE
Remove icon

### ISSUE THREAD

**Issue by Phyto-Matter-Johanna** [phyto-matter/phyto-matter#11]
<img width="216" alt="Screenshot 2023-12-06 at 13 14 06" src="https://github.com/phyto-matter/phyto-matter/assets/148214016/c897888b-c358-449f-9505-0e166318da33">

Take away this little image-icon.

**Comment by Mr-Squirrel** [comment]
that is a broken link. let me check why it's not loading

**Comment by Mr-Squirrel** [comment]
Currently missing icons for:
- Materials
  - decor
  - edges
  - details

**Comment by Phyto-Matter-Johanna** [comment]
You have all the icons you need - i have edited the spreadsheet to it matches the existing categories!

**Comment by Mr-Squirrel** [comment]
Confirmed, closing
