### ISSUE TITLE
Linking plants from materials page

### ISSUE THREAD

**Issue by Phyto-Matter-Johanna** [phyto-matter/phyto-matter#13]
When in a materials page ex https://phytomatter.web.app/materials/Linum-furniture the plant name (=genus) should be a link (in this case "Linum" should be linked to a plant search of that Plant genus showing the plants available. If only one plant with that genus, it could be linked into that specific plants page. If no plants with that genus, no link (rather than no result, if possible)

**Comment by Mr-Squirrel** [comment]
Done
