### ISSUE TITLE
Linking materials from plant page

### ISSUE THREAD

**Issue by Phyto-Matter-Johanna** [phyto-matter/phyto-matter#14]
When in a plant page (ex. https://phytomatter.web.app/plants/salix-viminalis), at the bottom below References, there should be a list of the related materials such as "Braided Salix", "Salix furniture", "Willow string,....", "Salix sculpture". No categories needed, and when many materials have the same material is should function in the same way as from the materials search that the projects are grouped together on the materials page.

**Comment by Mr-Squirrel** [comment]
Done
