### ISSUE TITLE
read-me link

### ISSUE THREAD

**Issue by Phyto-Matter-Johanna** [phyto-matter/phyto-matter#19]
In the intro text on the first page: the words "an open-source platform" can be a link to the README-file.

**Comment by Phyto-Matter-Johanna** [comment]
also this text further down on the first page can be a link to the same:  "We encourage participants and users of this tool to contact us with any feedback or ideas on how to develop newer versions in the future."

**Comment by Phyto-Matter-Johanna** [comment]
After this section: "Do you want to contribute? We welcome researchers and designers adding information to the open source knowledge pool using the very user-friendly upload system GitHub Pull Requests." 
Add:
"Click here to find out how!" and link it to the readme file.

**Comment by Mr-Squirrel** [comment]
done
