### ISSUE TITLE
Updated Acknowledgements - text for first page

### ISSUE THREAD

**Issue by Phyto-Matter-Johanna** [phyto-matter/phyto-matter#20]
Acknowledgements

The authors would like to thank all of the professionals, volunteers and participants who has been involved in the Phyto-matter project so far. The work was funded by SLU Holding and Sparbanken Skåne (partly through the Innovation Award 2023) which resulted in the short film by Filmbruket, this website and the open source GitHub platform. Thank you to those who contributed with their time and knowledge on the topics of phytoremediation and materials making. All of your insights have contributed in different ways. Thank you developer geniuses Hugo Bove and Nora Disewji, without you there would be no user interface and no one outside of the university would understand anything about this project. 

Especially thankful are we to our data contributors, researchers and experimental individuals who continue providing data and insights to this tool.

**Comment by Mr-Squirrel** [comment]
done
