### ISSUE TITLE
phyto-matter on smart phone

### ISSUE THREAD

**Issue by Phyto-Matter-Nina** [phyto-matter/phyto-matter#21]
the website looks messed up when viewed on a smart phone. Can you please offer a simplifies view that shows the home page intro, the video, and says that Phyto-Matter functionality works best from a computer browser?

**Comment by Meowmir** [comment]
I will look into it.

**Comment by Meowmir** [comment]
Fixed in #22

**Comment by Phyto-Matter-Nina** [comment]
mobile view still looks funky.

**Comment by Mr-Squirrel** [comment]
@Meowmir please merge the pr

**Comment by Meowmir** [comment]
merged and published, its live

**Comment by Phyto-Matter-Nina** [comment]
Wonderful! Thanks!
